[build]
directory = './functions/'
functions = './functions/'


[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netfliy/functions/:splat"
  status = 200

[[edge_functions]]
function = "hello"
path = "/test"


